name: Release Package

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4.0.0

    - name: Restore tools
      run: dotnet tool restore

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src

    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src

    - name: Pack
      run: dotnet pack --no-build -p:PackageVersion=${{ github.ref_name }} -p:PackageReleaseNotes=${{ github.event.release.html_url }} --output .
      working-directory: ./src

    - name: Publish
      run: dotnet nuget push "*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
      working-directory: ./src
